cache:
  - cache1 -> appveyor\cleanup-cache1.txt
  - cache2 -> appveyor\cleanup-cache1.txt, appveyor\cleanup-cache2.txt
  - cache3 -> appveyor\cleanup-cache1.txt, appveyor\cleanup-cache2.txt, appveyor\cleanup-cache3.txt

install:
  - git submodule update --init
  - SET PATH=%APPDATA%\cabal\bin;C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.0.1\bin;C:\ProgramData\chocolatey\lib\cabal\tools;C:\Program Files (x86)/WiX Toolset v3.10\bin;%PATH%
  - SET PKG_CONFIG_PATH=C:\msys64\mingw64\lib\pkgconfig
  - SET XDG_DATA_DIRS=C:\msys64\mingw64\share
  - pacman --version
  - appveyor-retry choco install ghc --version 8.0.1 | grep -v '^Extracting '
  - cabal --version
  - appveyor-retry choco install wixtoolset
  - heat -? | grep version
  - appveyor-retry choco install dejavufonts --version 2.35
  - appveyor-retry pacman -S -q --noconfirm mingw64/mingw-w64-x86_64-pkg-config mingw64/mingw-w64-x86_64-gobject-introspection mingw64/mingw-w64-x86_64-gtksourceview3 mingw64/mingw-w64-x86_64-webkitgtk3

#  # In the past not all packages were rebuilt with the new ICU and this work
#  # around was used to install an older version.  Leaving it here for now
#  # in case we need it again.
#  # The webkitgtk package still expects ICU 56
#  - appveyor-retry curl -fsSL -o mingw-w64-x86_64-icu-56.1-1-any.pkg.tar.xz https://sourceforge.net/projects/msys2/files/REPOS/MINGW/x86_64/mingw-w64-x86_64-icu-56.1-1-any.pkg.tar.xz/download
#  - pacman -U --noconfirm mingw-w64-x86_64-icu-56.1-1-any.pkg.tar.xz
#  - appveyor-retry curl -fsSL -o mingw-w64-x86_64-harfbuzz-1.2.7-1-any.pkg.tar.xz https://sourceforge.net/projects/msys2/files/REPOS/MINGW/x86_64/mingw-w64-x86_64-harfbuzz-1.2.7-1-any.pkg.tar.xz/download
#  - pacman -U --noconfirm mingw-w64-x86_64-harfbuzz-1.2.7-1-any.pkg.tar.xz

build_script:
  - chcp 65001 && bash -ex appveyor/build-some.sh

artifacts:
  - path: win32/*.msi
    name: Leksah Windows Installer